---
name: Bot-BasicBot-Pluggable-Module-RT
version: 0.02
author:
  - 'Damien "dams" Krotkine <dams@cpan.org>'
abstract: Retrieves information of RT tickets
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Bot::BasicBot::Pluggable: 0.5
  RT::Client::REST: 0
  RT::Client::REST::Ticket: 0
  Test::More: 0
provides:
  Bot::BasicBot::Pluggable::Module::RT:
    file: lib/Bot/BasicBot/Pluggable/Module/RT.pm
    version: 0.02
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
