---
abstract: 'This is a plugin to access information about RT tickets on IRC'
author:
  - "Damien \"dams\" Krotkine"
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110320'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-BasicBot-Pluggable-Module-RT
provides:
  Bot::BasicBot::Pluggable::Module::RT:
    file: lib/Bot/BasicBot/Pluggable/Module/RT.pm
    version: 0.20
requires:
  Bot::BasicBot::Pluggable::Module: 0
  RT::Client::REST: 0
  RT::Client::REST::Ticket: 0
resources:
  homepage: http://search.cpan.org/dist/Bot-BasicBot-Pluggable-Module-RT
  repository: http://github.com/dams/bot-basicbot-pluggable-module-rt
version: 0.20
